version: '3.7'

services:

    mtp:
        build:
            context: .
        command: npm run dev 

        ports:
          - "5000:5000"
        volumes:
            - .:/home/node/mtp
            - node_modules:/home/node/mtp/node_modules
        depends_on:
            - mysqlmtp
    mysqlmtp:
        image: mysql
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE
        environment:
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_DATABASE: "mtp"
          MYSQL_PASSWORD: "root"
        volumes:
            - mysql_data:/data/db
        ports:
          - "3306:3306"
          
volumes:
    node_modules:
    mysql_data: